name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKENN }} 
        run: git push --force https://hudamhmd:$HF_TOKEN@huggingface.co/spaces/hudamhmd/cbc-Diagnosis main
